Repository luc4sleite/goservice, pull requests merged in 2023-09, with the labels that each got.

#80 logo aplicada na pagina
  src/main/resources/static/css/main.css
  src/main/resources/templates/cadastroCliente.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/login.html
Labels: enhancement

#84 inserção do populate no banco de dados
  mysql/POPULATE.sql
  mysql/SCRIPT_INICIAL.sql
Labels: documentation, enhancement

#86 Footer
  src/main/resources/templates/agendaPrestador.html
  src/main/resources/templates/agendarServico.html
  src/main/resources/templates/alterarSenha.html
  src/main/resources/templates/dadosCliente.html
  src/main/resources/templates/dadosPrestador.html
  src/main/resources/templates/dashboard.html
  src/main/resources/templates/editarServico.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/historicoCliente.html
  src/main/resources/templates/home.html
  src/main/resources/templates/servicosAdmin.html
  src/main/resources/templates/usuariosAdmin.html
Labels: enhancement

#85 Criacao da consulta que busca numeros de usuarios perfil
  src/main/java/com/soulcode/goserviceapp/repository/UsuarioRepository.java
  src/main/java/com/soulcode/goserviceapp/service/UsuarioService.java
Labels: enhancement

#91 Correcao do codigo
  src/main/java/com/soulcode/goserviceapp/repository/UsuarioRepository.java
Labels: bug

#90 Perguntas frequentes
  src/main/java/com/soulcode/goserviceapp/config/SecurityConfig.java
  src/main/java/com/soulcode/goserviceapp/controller/DuvidasController.java
  src/main/resources/static/css/main.css
  src/main/resources/templates/duvidasFrequentes.html
Labels: documentation

#92 inclusão do modal para exibição dos detalhes do prestador no históric…
  src/main/resources/templates/historicoCliente.html
Labels: enhancement

#93 Inclusão do modal na agenda do prestador para exibir detalhes do cliente
  src/main/resources/templates/agendaPrestador.html
  src/main/resources/templates/historicoCliente.html
Labels: enhancement

#94 Criação dos cards na página principal
  src/main/resources/static/css/main.css
  src/main/resources/templates/home.html
Labels: enhancement

#96 Consulta status de agendamentos
  src/main/java/com/soulcode/goserviceapp/repository/AgendamentoRepository.java
Labels: enhancement

#97 criação do sistema de logs para os agendamentos
  src/main/java/com/soulcode/goserviceapp/domain/AgendamentoLog.java
  src/main/java/com/soulcode/goserviceapp/repository/AgendamentoLogRepository.java
  src/main/java/com/soulcode/goserviceapp/service/AgendamentoLogService.java
Labels: enhancement

#98 Exibição dos logs de agendamentos na área de dashboard do administrador
  mysql/POPULATE.sql
  src/main/java/com/soulcode/goserviceapp/controller/AdministradorController.java
  src/main/java/com/soulcode/goserviceapp/service/AgendamentoService.java
  src/main/resources/templates/dashboard.html
Labels: enhancement

#102 Melhorias na validacão dos dados no formulário
  src/main/resources/static/js/script.js
  src/main/resources/templates/agendarServico.html
  src/main/resources/templates/alterarSenha.html
  src/main/resources/templates/cadastroCliente.html
  src/main/resources/templates/dadosCliente.html
  src/main/resources/templates/dadosPrestador.html
  src/main/resources/templates/editarServico.html
  src/main/resources/templates/login.html
  src/main/resources/templates/servicosAdmin.html
  src/main/resources/templates/usuariosAdmin.html
Labels: enhancement

#103 criação da tabela endereço
  src/main/java/com/soulcode/goserviceapp/domain/Endereco.java
  src/main/java/com/soulcode/goserviceapp/domain/Usuario.java
  src/main/java/com/soulcode/goserviceapp/repository/EnderecoRepository.java
  src/main/java/com/soulcode/goserviceapp/repository/UsuarioRepository.java
  src/main/java/com/soulcode/goserviceapp/service/EnderecoService.java
  src/main/java/com/soulcode/goserviceapp/service/UsuarioService.java
  src/main/java/com/soulcode/goserviceapp/service/exceptions/EnderecoNaoEncontradoException.java
Labels: enhancement

#104 Feita a tabela com o percentual em gráfico de status de agendamentos
  src/main/java/com/soulcode/goserviceapp/controller/AdministradorController.java
  src/main/java/com/soulcode/goserviceapp/service/AgendamentoService.java
  src/main/resources/templates/servicosAdmin.html
Labels: enhancement

#105 verificação da data, para bloquear o agendamento de um serviço em uma…
  src/main/java/com/soulcode/goserviceapp/controller/ClienteController.java
  src/main/java/com/soulcode/goserviceapp/service/exceptions/DataAgendamentoInvalidaException.java
  src/main/resources/static/js/script.js
Labels: enhancement

#106 Feito a consulta para limitar até 10 usuarios por página
  src/main/java/com/soulcode/goserviceapp/repository/UsuarioRepository.java
Labels: enhancement

#107 criação de um metodo que possibilite a alteração de endereço.
  src/main/java/com/soulcode/goserviceapp/repository/EnderecoRepository.java
  src/main/java/com/soulcode/goserviceapp/service/EnderecoService.java
Labels: enhancement

#109 Criação dos métodos Lombok para substituir a utilização de Getters e …
  pom.xml
  src/main/java/com/soulcode/goserviceapp/domain/Agendamento.java
  src/main/java/com/soulcode/goserviceapp/domain/AgendamentoLog.java
  src/main/java/com/soulcode/goserviceapp/domain/Cliente.java
  src/main/java/com/soulcode/goserviceapp/domain/Endereco.java
  src/main/java/com/soulcode/goserviceapp/domain/Prestador.java
  src/main/java/com/soulcode/goserviceapp/domain/Servico.java
  src/main/java/com/soulcode/goserviceapp/domain/Usuario.java
  src/main/java/com/soulcode/goserviceapp/domain/UsuarioLog.java
Labels: enhancement

#110 Feita verificação de disponibilidade de horário por prestador e lançamento de erro
  src/main/java/com/soulcode/goserviceapp/controller/ClienteController.java
  src/main/java/com/soulcode/goserviceapp/repository/AgendamentoRepository.java
  src/main/java/com/soulcode/goserviceapp/service/AgendamentoService.java
  src/main/java/com/soulcode/goserviceapp/service/exceptions/HorarioAgendamentoNaoDisponivelException.java
Labels: enhancement

#111 Criação e mapeamento da pagina dados admin
  src/main/java/com/soulcode/goserviceapp/controller/AdministradorController.java
  src/main/java/com/soulcode/goserviceapp/repository/AdministradorRepository.java
  src/main/java/com/soulcode/goserviceapp/service/AdministradorService.java
  src/main/resources/templates/dadosAdmin.html
  src/main/resources/templates/duvidasFrequentes.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
Labels: enhancement

#112 criação do chat entre prestador em cliente.
  pom.xml
  src/main/java/com/soulcode/goserviceapp/controller/ClienteController.java
  src/main/java/com/soulcode/goserviceapp/controller/PrestadorController.java
  src/main/java/com/soulcode/goserviceapp/domain/Mensagem.java
  src/main/java/com/soulcode/goserviceapp/repository/MensagemRepository.java
  src/main/java/com/soulcode/goserviceapp/service/AgendamentoService.java
  src/main/java/com/soulcode/goserviceapp/service/ClienteService.java
  src/main/java/com/soulcode/goserviceapp/service/MensagemService.java
  src/main/java/com/soulcode/goserviceapp/service/exceptions/MensagemNaoEncontradaException.java
  src/main/resources/static/css/main.css
  src/main/resources/templates/agendaPrestador.html
  src/main/resources/templates/chatCliente.html
  src/main/resources/templates/chatPrestador.html
  src/main/resources/templates/historicoCliente.html
Labels: enhancement

#113 Add os Metodos Gettrer e Setter no domain Mensagem.
  src/main/java/com/soulcode/goserviceapp/domain/Mensagem.java
Labels: enhancement

#114 Criação da consulta de forma paginada para os serviços.
  src/main/java/com/soulcode/goserviceapp/repository/ServicoRepository.java
Labels: enhancement

#116 Criação de query para retornar os agendamento de forma paginada.
  src/main/java/com/soulcode/goserviceapp/repository/AgendamentoRepository.java
Labels: enhancement

#117 Implementação do filtro de busca do cliente
  src/main/java/com/soulcode/goserviceapp/controller/ClienteController.java
  src/main/java/com/soulcode/goserviceapp/repository/AgendamentoRepository.java
  src/main/java/com/soulcode/goserviceapp/service/AgendamentoService.java
  src/main/resources/templates/historicoCliente.html
Labels: enhancement

#118 Filtragem e consulta de todos usuarios pelo nome na página de administrador
  src/main/java/com/soulcode/goserviceapp/controller/AdministradorController.java
  src/main/java/com/soulcode/goserviceapp/repository/UsuarioRepository.java
  src/main/java/com/soulcode/goserviceapp/service/UsuarioService.java
  src/main/resources/templates/usuariosAdmin.html
Labels: enhancement

#119 Feita filtragem de busca de serviços por nome na area administrativa
  src/main/java/com/soulcode/goserviceapp/controller/AdministradorController.java
  src/main/java/com/soulcode/goserviceapp/repository/ServicoRepository.java
  src/main/java/com/soulcode/goserviceapp/service/ServicoService.java
  src/main/resources/templates/servicosAdmin.html
Labels: enhancement

#120 Cacheamento com Redis
  src/main/java/com/soulcode/goserviceapp/service/UsuarioService.java
Labels: enhancement

#122 Correção da utilização do css, utilizando bootstrap para os estilos
  src/main/resources/templates/home.html
Labels: bug

#123 aplicando o tooptip em quase todos os botões de site
  src/main/resources/static/js/script.js
  src/main/resources/templates/agendaPrestador.html
  src/main/resources/templates/agendarServico.html
  src/main/resources/templates/alterarEndereco.html
  src/main/resources/templates/alterarSenha.html
  src/main/resources/templates/cadastroCliente.html
  src/main/resources/templates/chatCliente.html
  src/main/resources/templates/chatPrestador.html
  src/main/resources/templates/dadosAdmin.html
  src/main/resources/templates/dadosCliente.html
  src/main/resources/templates/dadosPrestador.html
  src/main/resources/templates/editarServico.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/historicoCliente.html
  src/main/resources/templates/login.html
  src/main/resources/templates/servicosAdmin.html
  src/main/resources/templates/usuariosAdmin.html
Labels: enhancement

#124 Correção da configuração do redis
  src/main/java/com/soulcode/goserviceapp/domain/Usuario.java
  src/main/java/com/soulcode/goserviceapp/service/UsuarioService.java
  src/main/resources/application.properties
Labels: bug

#125 Carrossel
  src/main/resources/templates/home.html
Labels: enhancement

#126 fix: query para paginar a tabela de usuários na área do prestador
  src/main/java/com/soulcode/goserviceapp/domain/Usuario.java
  src/main/java/com/soulcode/goserviceapp/repository/UsuarioRepository.java
  src/main/java/com/soulcode/goserviceapp/service/UsuarioService.java
Labels: bug, enhancement

#127 Inclusão da páginação de usuários na área do administrador.
  src/main/java/com/soulcode/goserviceapp/controller/AdministradorController.java
  src/main/resources/templates/usuariosAdmin.html
Labels: enhancement

#128 Inclusão de paginação de serviços na área do administrado
  src/main/java/com/soulcode/goserviceapp/controller/AdministradorController.java
  src/main/java/com/soulcode/goserviceapp/repository/ServicoRepository.java
  src/main/java/com/soulcode/goserviceapp/service/ServicoService.java
  src/main/java/com/soulcode/goserviceapp/service/UsuarioService.java
  src/main/resources/templates/servicosAdmin.html
Labels: enhancement

#129 Correção do populate para a inclusão da endereço para os usuários
  mysql/POPULATE.sql
  mysql/SCRIPT_INICIAL.sql
Labels: bug, enhancement
